# POST /posts
# Description: Create a new post.
POST http://localhost:3000/posts
Content-Type: application/json
{
  "title": "New Post",
  "content": "This is a new post content.",
  "slug": "new-post",
  "postType": "post",
  "status": "published",
  "metaOptions": {
    "metaValue": "{\"sidebarEnabled\": true, \"theme\": \"dark\"}"
  }
}
