# POST /posts
# Description: Create a new post.
POST http://localhost:3000/posts
Content-Type: application/json
{
  "title": "New Post",
  "content": "This is a new post content.",
  "postType": "post",
  "slug": "new-post",
  "status": "draft",
  "metaOptions": [{
    "key": 1,
    "value": "John Doe"
  }]
}
