# POST /posts
# Description: Create a new post.
POST http://localhost:3000/posts
Content-Type: application/json
{
  "title": "Wow, this is NestJS in action!",
  "content": "This is a new post created using NestJS.",
  "slug": "wow-this-is-nestjs-in-action",
  "postType": "post",
  "status": "published",
  "metaOptions": {
    "metaValue": "{\"sidebarEnabled\": false, \"theme\": \"light\"}"
  },
  "authorId": ""
}
